version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: techway_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: ./course-management-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/techway_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8080
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build: ./techway
    depends_on:
      - backend
    ports:
      - "80:80"
    # ملاحظة: nginx.conf في الفرونت يروّت /api -> backend:8080

volumes:
  dbdata: {}
